In [2]:
import pandas as pd

In [4]:
#Leer el archivo csv usando pandas desde un website
df_premier25 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2526/E0.csv')

# LINKS: 
Premier League: https://www.football-data.co.uk/mmz4281/2425/E0.csv
Championship: https://www.football-data.co.uk/mmz4281/2425/E1.csv
League 1: https://www.football-data.co.uk/mmz4281/2425/E2.csv
League 2: https://www.football-data.co.uk/mmz4281/2425/E3.csv
Conference: https://www.football-data.co.uk/mmz4281/2425/EC.csv

# Estructura de un link
'https://www.football-data.co.uk/mmz4281/' + '2425' + '/' + 'E0' + '.csv'

In [31]:
#crear una variable root para los links
root = "https://www.football-data.co.uk/mmz4281/"

#crear lista de ligas
leagues = ['E0', 'E1']

#crear el loop en la lista de ligas, leer los csv y adjuntarlos en una variable con el m√©todo append.
#Hacer un loop para extraer las temporadas e insertarlas en una nueva columna

frames = []

for league in leagues:
   for season in range(15, 25):
      df = pd.read_csv(root + str(season) + str(season + 1) + '/' + league + '.csv', encoding='unicode_escape')
      df.insert(1, 'season', season)

      frames.append(df)

In [33]:
#Organizar data en un Diccionario 

dict_countries = {
    'Spanish La Liga' : 'SP1', 'Spanish Segunda Division' : 'SP2',
    'German Bundesliga': 'D1',
    'English Premier League' : 'E0', 'English Championship' : 'E1'
}

In [45]:
#crear un loop sobre las llaves del diccionario

dict_historico = {}


for league in dict_countries:
    frames = [] # un dataframe por liga

    for season in range(20, 25):
        df = pd.read_csv(root + str(season) + str(season+1) + "/" + dict_countries[league]+ ".csv")
        df.insert(1, 'season', season)
        frames.append(df)

    df_frames = pd.concat(frames) # almacenar todas las temporadas de la liga en un solo dataframe
    dict_historico[league] = df_frames # asignar dataframe a un nuevo diccionario

In [46]:
dict_historico['Spanish La Liga']

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,1XBCH,1XBCD,1XBCA,BFECH,BFECD,BFECA,BFEC>2.5,BFEC<2.5,BFECAHH,BFECAHA
0,SP1,20,12/09/2020,15:00,Eibar,Celta,0,0,D,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SP1,20,12/09/2020,17:30,Granada,Ath Bilbao,2,0,H,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SP1,20,12/09/2020,20:00,Cadiz,Osasuna,0,2,A,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SP1,20,13/09/2020,13:00,Alaves,Betis,0,1,A,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SP1,20,13/09/2020,15:00,Valladolid,Sociedad,1,1,D,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,SP1,24,24/05/2025,20:00,Getafe,Celta,1,2,A,1,...,4.85,3.88,1.77,5.30,3.9,1.79,2.08,1.89,1.95,2.03
376,SP1,24,24/05/2025,20:00,Vallecano,Mallorca,0,0,D,0,...,1.53,4.19,7.29,1.50,4.6,8.20,2.10,1.87,1.85,2.14
377,SP1,24,25/05/2025,13:00,Girona,Ath Madrid,0,4,A,0,...,3.48,3.57,2.16,3.50,3.7,2.24,1.60,2.64,2.04,1.94
378,SP1,24,25/05/2025,15:15,Villarreal,Sevilla,4,2,H,3,...,1.75,4.42,4.30,1.80,4.3,4.60,1.60,2.62,2.03,1.95
379,SP1,24,25/05/2025,20:00,Ath Bilbao,Barcelona,0,3,A,0,...,3.49,4.00,2.03,3.35,4.0,2.18,1.47,3.05,2.07,1.91